export const SET_CURSOR_POSITION = 'SET_CURSOR_POSITION';
export const SET_CURSOR_TARGET = 'SET_CURSOR_TARGET';
export const REMOVE_CURSOR_TARGET = 'REMOVE_CURSOR_TARGET';
export const SET_CURSOR_COLOR = 'SET_CURSOR_COLOR';
export const RESET_CURSOR_COLOR = 'RESET_CURSOR_COLOR';
export const SET_CURSOR_ACCENT = 'SET_CURSOR_ACCENT';
export const RESET_CURSOR_ACCENT = 'RESET_CURSOR_ACCENT';

export const FETCH_REPOS_REQUESTED = 'FETCH_REPOS_REQUESTED';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';
export const RESTORE_REPOS_FROM_STORAGE = 'RESTORE_REPOS_FROM_STORAGE';
